// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhdkxaixyfzcgnuqdnwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZGt4YWl4eWZ6Y2dudXFkbnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODAzMTksImV4cCI6MjA2MTA1NjMxOX0.fKSSIxh_42nJ7Ya3DeJ569vnJEVmc90jE5E1nlFb9yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);